/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Admin;

import Model.TaiKhoanModel;
import javax.swing.JOptionPane;


/**
 *
 * @author lamng
 */
public class DLSuaTaiKhoan extends javax.swing.JDialog{
    private int index;
    private TaiKhoanModel tk;
    public DLSuaTaiKhoan(java.awt.Frame parent, boolean modal, TaiKhoanModel tk, int index) {
        super(parent, modal);
        this.index = index;
        this.tk = tk;
        initComponents();
        setView(tk);
    }
    
    //Lấy thông tin tài khoản đã chọn và hiển thị ra form sửa
    public void setView(TaiKhoanModel tk) {
        txtMaGV.setVisible(false);
        txtMaGV.setText(String.valueOf(tk.getMaGV()));
        txtUsername.setText(tk.getUsername());
        txtPassword.setText(tk.getPassword());
        txtHoTen.setText(tk.getHoTen());
        datePkNgaySinh.setDate(tk.getNgaySinh());
        txtDiaChi.setText(tk.getDiaChi());
        txtEmail.setText(tk.getEmail());
        txtSDT.setText(tk.getSDT());
        if (tk.getQuyen() == 1) {
            cbQuyen.setSelectedIndex(0);
        } else {
            cbQuyen.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbQuyen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        txtMaGV = new javax.swing.JTextField();
        datePkNgaySinh = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(51, 153, 255));
        btnLuu.setText("Sửa tài khoản");
        btnLuu.setToolTipText("");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 150, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin giáo viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 30));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ngày sinh:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Địa chỉ:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 100, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 160, 30));

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Quyền:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số điện thoại:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 100, 30));

        cbQuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Thông thường:" }));
        jPanel2.add(cbQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 160, 30));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        txtMaGV.setEditable(false);
        jPanel2.add(txtMaGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, -1));

        datePkNgaySinh.setDateFormatString("dd/MM/yyyy");
        datePkNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(datePkNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 180, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 33, 170, 0));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (txtPassword.getText().isEmpty() || txtHoTen.getText().isEmpty() || 
            txtUsername.getText().isEmpty() || txtDiaChi.getText().isEmpty() || txtEmail.getText().isEmpty()||
                txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
        } else {
            TaiKhoanModel tkNew = new TaiKhoanModel();
            tkNew.setMaGV(Integer.parseInt(txtMaGV.getText()));
            String username = txtUsername.getText();
            if (JPQLTaiKhoan.jpQLTaiKhoan.isExistUsername(username) && !tk.getUsername().equals(username)) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại");
                txtUsername.requestFocus();
            } else {
                tkNew.setUsername(txtUsername.getText());
                tkNew.setPassword(txtPassword.getText());
                tkNew.setHoTen(txtHoTen.getText());        
                tkNew.setNgaySinh(datePkNgaySinh.getDate());
                tkNew.setDiaChi(txtDiaChi.getText());
                tkNew.setEmail(txtEmail.getText());
                if (cbQuyen.getSelectedItem().toString().equals("Admin")) {
                tkNew.setQuyen(1);           
                } else {
                    tkNew.setQuyen(0);
                }

                try {
                    tkNew.setSDT(txtSDT.getText());
                    JPQLTaiKhoan.jpQLTaiKhoan.suaTaiKhoan(tkNew, index);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    JPQLTaiKhoan.jpQLTaiKhoan.loadTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ");
                }
            }   
        }
    }//GEN-LAST:event_btnLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbQuyen;
    private com.toedter.calendar.JDateChooser datePkNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
