/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI.Admin;

import Model.PhongTHModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lamng
 */
public class DLSuaPhongTH extends javax.swing.JDialog {

    private int index;
    private PhongTHModel pth;
    
    public DLSuaPhongTH(java.awt.Frame parent, boolean modal, PhongTHModel pth, int index) {
        super(parent, modal);
        initComponents();
        this.pth = pth;
        this.index = index;
        setView(pth);
    }
    
    //Lấy thông tin phòng thực hành đã chọn và hiển thị ra form sửa
    public void setView(PhongTHModel pth) {
        txtMaPhong.setText(pth.getMaPhong());
        txtTenPhong.setText(pth.getTenPhong());
        cbToaNha.setSelectedItem(pth.getToaNha());
        cbTang.setSelectedItem(pth.getTang());
        txtCauHinh.setText(pth.getCauHinh());
        txtSoMay.setText(String.valueOf(pth.getSoMay()));
        txtTinhTrang.setText(pth.getTinhTrang());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoMay = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCauHinh = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cbToaNha = new javax.swing.JComboBox<>();
        cbTang = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng thực hành", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã phòng:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 30));

        txtMaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tòa nhà");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên phòng:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tầng:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cấu hình:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số máy:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, 30));

        txtSoMay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSoMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 70, 30));

        txtTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 210, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tình trạng:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, 30));

        txtCauHinh.setColumns(20);
        txtCauHinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCauHinh.setRows(5);
        jScrollPane1.setViewportView(txtCauHinh);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 230, 90));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 180, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 33, 170, 0));

        cbToaNha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "C1" }));
        jPanel2.add(cbToaNha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 50, 30));

        cbTang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        jPanel2.add(cbTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 50, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 270));

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(51, 153, 255));
        btnLuu.setText("Sửa phòng thực hành");
        btnLuu.setToolTipText("");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (txtTenPhong.getText().isEmpty() ||
            txtMaPhong.getText().isEmpty() || txtCauHinh.getText().isEmpty() || txtSoMay.getText().isEmpty()||
            txtTinhTrang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(btnLuu, "Vui lòng nhập đầy đủ");
        } else {
            PhongTHModel pthNew = new PhongTHModel();
            pthNew.setMaPhong(txtMaPhong.getText());
            if (JPQLPhongTH.jPQLPhongTH.getListPhongTH().contains(pthNew)&& !pth.getMaPhong().equals(pthNew.getMaPhong())) {
                JOptionPane.showMessageDialog(btnLuu, "Mã phòng đã tồn tại");
            } else {
                pthNew.setTenPhong(txtTenPhong.getText());
                pthNew.setTang(Integer.parseInt(cbTang.getSelectedItem().toString()));
                pthNew.setToaNha(cbToaNha.getSelectedItem().toString());
                pthNew.setCauHinh(txtCauHinh.getText());
                pthNew.setTinhTrang(txtTinhTrang.getText());
                try {
                    pthNew.setSoMay(Integer.parseInt(txtSoMay.getText()));
                    JPQLPhongTH.jPQLPhongTH.suaPhongTH(pthNew, index);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    JPQLPhongTH.jPQLPhongTH.loadTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Số máy phải là số nguyên dương");
                }
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbTang;
    private javax.swing.JComboBox<String> cbToaNha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtCauHinh;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtSoMay;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
