/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI.Admin;

import Model.LopHocModel;
import Model.MonHocModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lamng
 */
public class DLSuaMonTH extends javax.swing.JDialog {

    private MonHocModel mh;
    private int index;
    public DLSuaMonTH(java.awt.Frame parent, boolean modal, MonHocModel mh, int index) {
        super(parent, modal);
        this.mh = mh;
        this.index = index;
        initComponents();
        setView(mh);
    }

    //Lấy thông tin môn đã chọn và hiển thị ra form sửa
    public void setView(MonHocModel mh) {
        txtMaMon.setText(mh.getMaMH());
        txtTenMon.setText(mh.getTenMH());
        txtSoTinChi.setText(String.valueOf(mh.getSoTinChi()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSoTinChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin môn thực hành", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Số tín chỉ:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        txtSoTinChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtSoTinChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã môn:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 30));

        txtMaMon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên môn:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 30));

        txtTenMon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtTenMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 180));

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(51, 153, 255));
        btnLuu.setText("Sửa môn thực hành");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (txtSoTinChi.getText().isEmpty() || txtMaMon.getText().isEmpty() || txtTenMon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
        } else {
            MonHocModel mhNew = new MonHocModel();
            mhNew.setMaMH(txtMaMon.getText());
            if (JPQLMonTH.jpQLMon.getListMon().contains(mhNew) && !mh.getMaMH().equals(mhNew.getMaMH())) {
                JOptionPane.showMessageDialog(null, "Mã môn đã tồn tại");
            } else {
                mhNew.setTenMH(txtTenMon.getText());
                try {
                    mhNew.setSoTinChi(Integer.parseInt(txtSoTinChi.getText()));
                    JPQLMonTH.jpQLMon.suaMon(mhNew, index);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    JPQLMonTH.jpQLMon.loadTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Số lượng tín chỉ phải nguyên dương");
                }
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtSoTinChi;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
