/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Dao.PhieuDangKyDAO;
import FileHandle.FileHandleImp;
import Model.PhieuDangKyModel;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class JPQLLichTH extends javax.swing.JPanel {

    private ArrayList<PhieuDangKyModel> listPhieuDangKy;
    private FileHandleImp fileHandle;
    
    public JPQLLichTH() {
        fileHandle = new FileHandleImp();
        listPhieuDangKy = fileHandle.getDSPhieuDK();
        initComponents();
        loadTable();
    }
    
    //Lấy danh sách phiếu đăng ký theo mã phiếu
    public PhieuDangKyModel getPhieuDKByMaPhieu(int maPhieu) {
        for (PhieuDangKyModel pdk : listPhieuDangKy) {
            if(pdk.getMaPhieu() == maPhieu) {
                return pdk;
            }
        }
        return null;
    }

    public void loadTable() {
        tbPhieuDangKy.setModel(new PhieuDangKyDAO(listPhieuDangKy));
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tbPhieuDangKy.getModel());
        tbPhieuDangKy.setRowSorter(rowSorter);
        
        //Lọc theo trạng thái
        cboTrangThai.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = cboTrangThai.getSelectedItem().toString();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
        });
        
        //Set header
        tbPhieuDangKy.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    }
    
    //Cập nhật trạng thái
    public void setTrangThai(String trangThai) {
        int selectedRowIndex = tbPhieuDangKy.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn phiếu đăng ký nào !");
        } else {
            int maPhieu = (int) tbPhieuDangKy.getValueAt(selectedRowIndex, 1);
            PhieuDangKyModel pdkOld = getPhieuDKByMaPhieu(maPhieu);
            PhieuDangKyModel pdkNew = pdkOld;
            pdkNew.setTrangThai(trangThai);
            listPhieuDangKy.set(listPhieuDangKy.indexOf(pdkOld), pdkNew);
            fileHandle.ghiDSPhieuDK(listPhieuDangKy);
        }     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnDuyet = new javax.swing.JButton();
        btnTuChoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhieuDangKy = new javax.swing.JTable();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản lý lịch thực hành");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, -1));

        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDuyet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDuyet.setForeground(new java.awt.Color(0, 0, 255));
        btnDuyet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aprrove.png"))); // NOI18N
        btnDuyet.setText("Duyệt");
        btnDuyet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyetActionPerformed(evt);
            }
        });
        jPanel3.add(btnDuyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 120, 60));

        btnTuChoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTuChoi.setForeground(new java.awt.Color(255, 0, 0));
        btnTuChoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btnTuChoi.setText("Từ chối");
        btnTuChoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTuChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuChoiActionPerformed(evt);
            }
        });
        jPanel3.add(btnTuChoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 120, 60));

        tbPhieuDangKy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPhieuDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbPhieuDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbPhieuDangKy.setRowHeight(24);
        jScrollPane1.setViewportView(tbPhieuDangKy);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 710, 320));

        cboTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chờ duyệt", "Đã duyệt", "Từ chối" }));
        cboTrangThai.setSelectedIndex(-1);
        jPanel3.add(cboTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hiển thị các phiếu:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 938, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyetActionPerformed
        setTrangThai("Đã duyệt");
        loadTable();
    }//GEN-LAST:event_btnDuyetActionPerformed

    private void btnTuChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuChoiActionPerformed
        setTrangThai("Từ chối");
        loadTable();
    }//GEN-LAST:event_btnTuChoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuyet;
    private javax.swing.JButton btnTuChoi;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbPhieuDangKy;
    // End of variables declaration//GEN-END:variables
}
