/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Dao.PhongTHDAO;
import FileHandle.FileHandleImp;
import Model.PhongTHModel;
import Test.test;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lamng
 */
public class JPQLPhongTH extends javax.swing.JPanel {

    private ArrayList<PhongTHModel> listPhongTH;
    private FileHandleImp fileHandle;
    
    public static JPQLPhongTH jPQLPhongTH;
    public JPQLPhongTH() {
        jPQLPhongTH = this;
        fileHandle = new FileHandleImp();
        listPhongTH = fileHandle.getDSPhongTH();
        initComponents();
        loadTable();
    }
    
    public void loadTable() {
        tbPhongTH.setModel(new PhongTHDAO(listPhongTH));
        //Để sắp xếp bảng
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tbPhongTH.getModel());
        tbPhongTH.setRowSorter(rowSorter);
        //Lấy kí tự nhập vào form tìm kiếm
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            //Mỗi khi thêm kí tự
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            
            //Mỗi khi xóa kí tự
            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        //Set header
        tbPhongTH.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    }
    
    public void ghiDSPhongTH() {
        fileHandle.ghiDSPhongTH(listPhongTH);
    }
    
    public void themPhongTH(PhongTHModel pth) {
        listPhongTH.add(pth);
        ghiDSPhongTH();
    }
    
    public void suaPhongTH(PhongTHModel pth, int index) {
        listPhongTH.set(index, pth);
        ghiDSPhongTH();
    }
    
    public void xoaPhongTH(int index) {
        listPhongTH.remove(index);
        ghiDSPhongTH();
    }

    public ArrayList<PhongTHModel> getListPhongTH() {
        return listPhongTH;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhongTH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản lý phòng thực hành");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, -1));

        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 100, 60));
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 100, 60));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 100, 60));

        tbPhongTH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPhongTH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbPhongTH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbPhongTH.setRowHeight(24);
        jScrollPane1.setViewportView(tbPhongTH);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 710, 320));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 938, 480));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 938, 499));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DLThemPhongTH themPhongTH = new DLThemPhongTH(test.jfmainAdmin, true);
        themPhongTH.setTitle("Thêm phòng thực hành mới");
        themPhongTH.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        int selectedRowIndex = tbPhongTH.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn phòng nào !");
        } else {
            String maPhong = tbPhongTH.getValueAt(selectedRowIndex, 1).toString();
            PhongTHModel pthXoa = new PhongTHModel(maPhong);
            
            //Hiển thị xác nhận xóa
            int qs;
            qs = JOptionPane.showConfirmDialog(null, "Xóa phòng có mã: " + maPhong, "Xóa phòng", JOptionPane.YES_NO_OPTION);
            if (qs == JOptionPane.YES_OPTION){
                xoaPhongTH(listPhongTH.indexOf(pthXoa));
                loadTable();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //Lấy thông tin phòng thực hành đã chọn và mở form sửa khi nhấn nút sửa
        int selectedRowIndex = tbPhongTH.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn phòng nào !");
        } else {
            PhongTHModel pth = new PhongTHModel();
            pth.setMaPhong(tbPhongTH.getValueAt(selectedRowIndex, 1).toString());
            pth.setTenPhong(tbPhongTH.getValueAt(selectedRowIndex, 2).toString());
            pth.setTang((int)tbPhongTH.getValueAt(selectedRowIndex, 3));
            pth.setToaNha(tbPhongTH.getValueAt(selectedRowIndex, 4).toString());
            pth.setCauHinh(tbPhongTH.getValueAt(selectedRowIndex, 5).toString());
            try {
                pth.setSoMay((int)tbPhongTH.getValueAt(selectedRowIndex, 6));
                pth.setTinhTrang(tbPhongTH.getValueAt(selectedRowIndex, 7).toString());
                
                //Truyền pth từ lựa chọn trên bảng vào form sửa
                DLSuaPhongTH dlSuaPhong = new DLSuaPhongTH(test.jfmainAdmin, true, pth, listPhongTH.indexOf(pth));
                dlSuaPhong.setTitle("Sửa thông tin phòng thực hành");
                dlSuaPhong.setVisible(true);
            } catch (Exception e) {
                
            }  
        }

    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbPhongTH;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
