/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Dao.MonHocDAO;
import FileHandle.FileHandleImp;
import Model.MonHocModel;
import Test.test;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lamng
 */
public class JPQLMonTH extends javax.swing.JPanel {

    private ArrayList<MonHocModel> listMon;
    private FileHandleImp fileHandle;
    
    public static JPQLMonTH jpQLMon;
    public JPQLMonTH() {
        jpQLMon = this;
        fileHandle = new FileHandleImp();
        listMon = fileHandle.getDSMon();
        initComponents();
        loadTable();
    }
    
    public void loadTable() {
        tbMonHoc.setModel(new MonHocDAO(listMon));
        //Để sắp xếp bảng
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tbMonHoc.getModel());
        tbMonHoc.setRowSorter(rowSorter);
        
        //Lấy kí tự nhập vào form tìm kiếm
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            //Mỗi khi thêm kí tự
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            
            //Mỗi khi xóa kí tự
            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        
        tbMonHoc.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    }
    
    public void ghiDSMon() {
        fileHandle.ghiDSMon(listMon);
    }
    
    public void themMon(MonHocModel mh) {
        listMon.add(mh);
        ghiDSMon();
    }
    
    public void suaMon(MonHocModel mh, int index) {
        listMon.set(index, mh);
        ghiDSMon();
    }
    
    public void xoaMon(int index) {
        listMon.remove(index);
        ghiDSMon();
    }

    public ArrayList<MonHocModel> getListMon() {
        return listMon;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMonHoc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản lý môn thực hành");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, -1));

        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 100, 60));
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 100, 60));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 100, 60));

        tbMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbMonHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbMonHoc.setRowHeight(24);
        jScrollPane1.setViewportView(tbMonHoc);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 710, 320));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 938, 480));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 938, 499));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DLThemMonTH themMonTH = new DLThemMonTH(test.jfmainAdmin, true);
        themMonTH.setTitle("Thêm môn thực hành mới");
        themMonTH.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
        int selectedRowIndex = tbMonHoc.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn môn nào !");
        } else {
            String maMon = tbMonHoc.getValueAt(selectedRowIndex, 1).toString();
            MonHocModel mhXoa = new MonHocModel(maMon);
            
            //Hiển thị xác nhận xóa
            int qs;
            qs = JOptionPane.showConfirmDialog(null, "Xóa môn: " + maMon, "Xóa môn", JOptionPane.YES_NO_OPTION);
            if (qs == JOptionPane.YES_OPTION){
                xoaMon(listMon.indexOf(mhXoa));
                loadTable();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //Lấy thông tin môn thực hành đã chọn và mở form sửa khi nhấn nút sửa
        int selectedRowIndex = tbMonHoc.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn môn học nào !");
        } else {
            MonHocModel mh = new MonHocModel();
            mh.setMaMH(tbMonHoc.getValueAt(selectedRowIndex, 1).toString());
            mh.setTenMH(tbMonHoc.getValueAt(selectedRowIndex, 2).toString());
            try {
                mh.setSoTinChi((int)tbMonHoc.getValueAt(selectedRowIndex, 3));

                //Truyền mh từ lựa chọn trên bảng vào form sửa
                DLSuaMonTH dlSuaMon = new DLSuaMonTH(test.jfmainAdmin, true, mh, listMon.indexOf(mh));
                dlSuaMon.setTitle("Sửa thông tin môn học");
                dlSuaMon.setVisible(true);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbMonHoc;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
