/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.Admin.JPQLTaiKhoan;
import UI.Admin.JPQLPhongTH;
import UI.Admin.JPQLLichTH;
import Test.test;
import UI.NormalUser.JPDangKyLich;
import UI.NormalUser.JPDoiMatKhau;
import UI.NormalUser.JPThayDoiTT;
import UI.NormalUser.JPThongKeLichTH;
import java.awt.BorderLayout;

/**
 *
 * @author lamng
 */
public class JFMainNormalUser extends javax.swing.JFrame {

    public JFMainNormalUser() {
        initComponents();
        jlbHoTen.setText(test.tk.getHoTen());
    }
    
    // Danh sách các panel cần gọi
    JPDangKyLich jpDangKyLich;
    JPThongKeLichTH jpThongKeLichTH;
    JPThayDoiTT jpThayDoiTT;
    JPDoiMatKhau jpDoiMatKhau;
    
    //Load panel ra màn hình
    public void reloadPanel(int i) {
        JPLayout.removeAll();
        JPLayout.setLayout(new BorderLayout());
        JPLayout.validate();
        switch (i) {
            case 1:
                if (jpDangKyLich == null) {
                    jpDangKyLich = new JPDangKyLich();
                } 
                JPLayout.add(jpDangKyLich);
                break;
            case 2:
                if (jpThongKeLichTH == null) {
                    jpThongKeLichTH = new JPThongKeLichTH();
                }

                JPLayout.add(jpThongKeLichTH);
                break;
            case 3:
                if(jpThayDoiTT == null){
                    jpThayDoiTT = new JPThayDoiTT();
                }

                JPLayout.add(jpThayDoiTT);
                break;
             case 4:
                if(jpDoiMatKhau == null){
                    jpDoiMatKhau = new JPDoiMatKhau();
                }

                JPLayout.add(jpDoiMatKhau);
                break; 
            default:
                break;
        }
        JPLayout.updateUI();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbHoTen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPMenu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jlbThongKeLich = new javax.swing.JLabel();
        jlbĐangKyLich = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlbCapNhatTTCaNhan = new javax.swing.JLabel();
        jlbDoiMatKhau = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        JPLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Xin chào");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 30));

        jlbHoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbHoTen.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoTen.setText("jLabel7");
        jPanel1.add(jlbHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-white.png"))); // NOI18N
        jLabel2.setText("Đăng xuất");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 100, 30));

        JPMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 38, 221, 10));

        jlbThongKeLich.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbThongKeLich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar-interface-symbol-tool.png"))); // NOI18N
        jlbThongKeLich.setText("Thống kê lịch thực hành");
        jlbThongKeLich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbThongKeLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbThongKeLichMouseClicked(evt);
            }
        });
        JPMenu.add(jlbThongKeLich, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 40));

        jlbĐangKyLich.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbĐangKyLich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.png"))); // NOI18N
        jlbĐangKyLich.setText("Đăng ký lịch thực hành");
        jlbĐangKyLich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbĐangKyLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbĐangKyLichMouseClicked(evt);
            }
        });
        JPMenu.add(jlbĐangKyLich, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 40));
        JPMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, 221, 10));
        JPMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 221, 10));

        jlbCapNhatTTCaNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbCapNhatTTCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jlbCapNhatTTCaNhan.setText("Cập nhật thông tin cá nhân");
        jlbCapNhatTTCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbCapNhatTTCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCapNhatTTCaNhanMouseClicked(evt);
            }
        });
        JPMenu.add(jlbCapNhatTTCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 40));

        jlbDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/padlock.png"))); // NOI18N
        jlbDoiMatKhau.setText("Đổi mật khẩu");
        jlbDoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbDoiMatKhauMouseClicked(evt);
            }
        });
        JPMenu.add(jlbDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 40));
        JPMenu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 221, 10));

        JPLayout.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout JPLayoutLayout = new javax.swing.GroupLayout(JPLayout);
        JPLayout.setLayout(JPLayoutLayout);
        JPLayoutLayout.setHorizontalGroup(
            JPLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        JPLayoutLayout.setVerticalGroup(
            JPLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        test.login();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jlbĐangKyLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbĐangKyLichMouseClicked
        reloadPanel(1);
    }//GEN-LAST:event_jlbĐangKyLichMouseClicked

    private void jlbThongKeLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbThongKeLichMouseClicked
        reloadPanel(2);
    }//GEN-LAST:event_jlbThongKeLichMouseClicked

    private void jlbCapNhatTTCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCapNhatTTCaNhanMouseClicked
        reloadPanel(3);
    }//GEN-LAST:event_jlbCapNhatTTCaNhanMouseClicked

    private void jlbDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbDoiMatKhauMouseClicked
        reloadPanel(4);
    }//GEN-LAST:event_jlbDoiMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLayout;
    private javax.swing.JPanel JPMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlbCapNhatTTCaNhan;
    private javax.swing.JLabel jlbDoiMatKhau;
    private javax.swing.JLabel jlbHoTen;
    private javax.swing.JLabel jlbThongKeLich;
    private javax.swing.JLabel jlbĐangKyLich;
    // End of variables declaration//GEN-END:variables
}
