/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI.NormalUser;

import FileHandle.FileHandleImp;
import Model.LopHocModel;
import Model.MonHocModel;
import Model.PhieuDangKyModel;
import Model.PhongTHModel;
import Model.TaiKhoanModel;
import Test.test;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lamng
 */
public class DLDangKyLich extends javax.swing.JDialog {

    private ArrayList<PhieuDangKyModel> listPhieuDK;
    private FileHandleImp fileHandle;
    public DLDangKyLich(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        fileHandle = new FileHandleImp();
        initComponents();
        loadTable();
    }
    
    public void loadTable() {
        listPhieuDK = fileHandle.getDSPhieuDK();
        //Set header
        tbDSDaDangKy.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        //Ten cac cot
        String col[] = {"STT","Giáo viên", "Mã lớp", "Mã môn", "Mã phòng", "Ca", "Thứ", "Từ ngày", "Đến ngày"};
        DefaultTableModel model = new DefaultTableModel(col, 0);
        int stt = 0;
        SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
        for (PhieuDangKyModel pdk : listPhieuDK) {
            if(!pdk.getTrangThai().equals("Từ chối")) {
                stt++;
                Object[] obj = {stt, pdk.getTk().getHoTen(), pdk.getLh().getMaLop(), pdk.getMh().getMaMH(), 
                pdk.getPth().getMaPhong(), pdk.getCa(), pdk.getThu(), 
                fm.format(pdk.getTuNgay()), fm.format(pdk.getDenNgay())};
                model.addRow(obj);
            }
        }
        
        tbDSDaDangKy.setModel(model);
        
        //Để sắp xếp
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tbDSDaDangKy.getModel());
        tbDSDaDangKy.setRowSorter(rowSorter);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboMaLop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboCa = new javax.swing.JComboBox<>();
        cboThu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datePkTuNgay = new com.toedter.calendar.JDateChooser();
        datePkDenNgay = new com.toedter.calendar.JDateChooser();
        cboMaPhong = new javax.swing.JComboBox<>();
        cboMaMon = new javax.swing.JComboBox<>();
        btnDangKy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSDaDangKy = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đăng ký", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã lớp:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 30));

        cboMaLop.setModel(new DefaultComboBoxModel(JPDangKyLich.jpDangKyLich.getListMaLop().toArray())
        );
        jPanel1.add(cboMaLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 32, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mã môn:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã phòng:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Đến ngày:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 70, 30));

        cboCa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "C", "T" }));
        jPanel1.add(cboCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 60, 30));

        cboThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ Nhật" }));
        jPanel1.add(cboThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ca:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 40, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Thứ:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 40, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Từ ngày:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 70, 30));

        datePkTuNgay.setDateFormatString("dd/MM/yyyy");
        datePkTuNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datePkTuNgay.setMaxSelectableDate(new java.util.Date(253370743277000L));
        datePkTuNgay.setMinSelectableDate(new java.util.Date(-62135791123000L));
        jPanel1.add(datePkTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 160, 30));

        datePkDenNgay.setDateFormatString("dd/MM/yyyy");
        datePkDenNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(datePkDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 160, 30));

        cboMaPhong.setModel(new DefaultComboBoxModel(JPDangKyLich.jpDangKyLich.getListMaPhong().toArray())
        );
        jPanel1.add(cboMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, 30));

        cboMaMon.setModel(new DefaultComboBoxModel(JPDangKyLich.jpDangKyLich.getListMaMon().toArray())
        );
        jPanel1.add(cboMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, 30));

        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(51, 153, 255));
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 910, 210));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách đăng ký", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setRequestFocusEnabled(false);

        tbDSDaDangKy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbDSDaDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Giáo viên", "Mã lớp", "Mã môn", "Mã phòng", "Ca", "Thứ", "Từ ngày", "Đến ngày"
            }
        ));
        tbDSDaDangKy.setRowHeight(24);
        jScrollPane1.setViewportView(tbDSDaDangKy);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 910, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        if (datePkTuNgay.getDate() == null || datePkDenNgay.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
        } else {
            Date tuNgay = datePkTuNgay.getDate();
            Date denNgay = datePkDenNgay.getDate();
            //Kiểm tra tuNgay phai < denNgay
            if(tuNgay.compareTo(denNgay) >= 0) {
                JOptionPane.showMessageDialog(null, "Ngày bắt đầu hoặc ngày kết thúc không hợp lệ");
            } else {
                PhieuDangKyModel pdk = new PhieuDangKyModel();
                int lastId = JPDangKyLich.jpDangKyLich.getLastId();
                pdk.setMaPhieu(lastId + 1);
                pdk.setTk(new TaiKhoanModel(test.tk.getMaGV(), test.tk.getHoTen()));
                pdk.setLh(new LopHocModel(cboMaLop.getSelectedItem().toString()));
                pdk.setMh(new MonHocModel(cboMaMon.getSelectedItem().toString()));
                String maPhong = cboMaPhong.getSelectedItem().toString();
                String ca = cboCa.getSelectedItem().toString();
                String thu = cboThu.getSelectedItem().toString();
                pdk.setTrangThai("Chờ duyệt");
                //Kiem tra trung lich
                if (JPDangKyLich.jpDangKyLich.isTrungLich(maPhong, ca, thu, tuNgay, denNgay)) {
                    JOptionPane.showMessageDialog(null, "Lịch bị trùng");
                } else {
                    pdk.setPth(new PhongTHModel(maPhong));
                    pdk.setCa(ca);
                    pdk.setThu(thu);
                    pdk.setTuNgay(tuNgay);
                    pdk.setDenNgay(denNgay);
                    JPDangKyLich.jpDangKyLich.themPhieuDangKy(pdk);
                    JOptionPane.showMessageDialog(null, "Đăng ký thành công");
                    JPDangKyLich.jpDangKyLich.loadTable();
                    this.loadTable();
                }
            }
            
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JComboBox<String> cboCa;
    private javax.swing.JComboBox<String> cboMaLop;
    private javax.swing.JComboBox<String> cboMaMon;
    private javax.swing.JComboBox<String> cboMaPhong;
    private javax.swing.JComboBox<String> cboThu;
    private com.toedter.calendar.JDateChooser datePkDenNgay;
    private com.toedter.calendar.JDateChooser datePkTuNgay;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDSDaDangKy;
    // End of variables declaration//GEN-END:variables
}
