/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NormalUser;

import FileHandle.FileHandleImp;
import Model.TaiKhoanModel;
import Test.test;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lamng
 */
public class JPDoiMatKhau extends javax.swing.JPanel {

    private ArrayList<TaiKhoanModel> listTK;
    private FileHandleImp fileHandle;
    private TaiKhoanModel tkLoggedIn;
    public JPDoiMatKhau() {
        fileHandle = new FileHandleImp();
        listTK = fileHandle.getDSTaiKhoan();
        tkLoggedIn = test.tk;
        initComponents();
    }

    public void suaTaiKhoan(TaiKhoanModel tk, int index) {
        listTK.set(index, tk);
        fileHandle.ghiDSTaiKhoan(listTK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtMatKhauHT = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtMkMoi = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtXacNhanMk = new javax.swing.JPasswordField();
        btnXacNhan = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu hiện tại:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 670, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Đổi mật khẩu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 30));
        jPanel1.add(txtMatKhauHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, 30));
        jPanel1.add(txtMkMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 260, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Xác nhận mật khẩu:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, 30));
        jPanel1.add(txtXacNhanMk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 260, 30));

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(51, 153, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 110, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 710, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String matKhauHienTai = String.valueOf(txtMatKhauHT.getPassword());
        String matKhauMoi = String.valueOf(txtMkMoi.getPassword());
        String xacNhanMk = String.valueOf(txtXacNhanMk.getPassword());
        
        if(matKhauHienTai.isEmpty() || matKhauMoi.isEmpty() || xacNhanMk.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        } else if (!matKhauHienTai.equals(test.tk.getPassword())) {
            JOptionPane.showMessageDialog(null, "Mật khẩu hiện tại không đúng");
        } else if (!matKhauMoi.equals(xacNhanMk)) {
            JOptionPane.showMessageDialog(null, "Mật khẩu xác nhận không trùng khớp");
        } else {
            TaiKhoanModel tkOld = new TaiKhoanModel(tkLoggedIn.getUsername(), tkLoggedIn.getPassword());
            tkLoggedIn.setPassword(matKhauMoi);
            suaTaiKhoan(tkLoggedIn, listTK.indexOf(tkOld));
            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtMatKhauHT;
    private javax.swing.JPasswordField txtMkMoi;
    private javax.swing.JPasswordField txtXacNhanMk;
    // End of variables declaration//GEN-END:variables
}
