/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NormalUser;

import FileHandle.FileHandleImp;
import Model.TaiKhoanModel;
import Test.test;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lamng
 */
public class JPThayDoiTT extends javax.swing.JPanel {

    private ArrayList<TaiKhoanModel> listTK;
    private FileHandleImp fileHandle;
    private TaiKhoanModel tkLoggedIn;
    
    public JPThayDoiTT() {
        tkLoggedIn = test.tk;
        fileHandle = new FileHandleImp();
        listTK = fileHandle.getDSTaiKhoan();
        initComponents();
        jlbUsername.setText(tkLoggedIn.getUsername());
        setView();
    }
    
    public void setView() {
        txtHoTen.setText(tkLoggedIn.getHoTen());
        datePkNgaySinh.setDate(tkLoggedIn.getNgaySinh());
        txtDiaChi.setText(tkLoggedIn.getDiaChi());
        txtEmail.setText(tkLoggedIn.getEmail());
        txtSDT.setText(tkLoggedIn.getSDT());
    }
    
    public void suaTaiKhoan(TaiKhoanModel tk, int index) {
        listTK.set(index, tk);
        fileHandle.ghiDSTaiKhoan(listTK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtHoTen = new javax.swing.JTextField();
        datePkNgaySinh = new com.toedter.calendar.JDateChooser();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlbUsername = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 450, 30));

        datePkNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(datePkNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, 30));

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 450, 30));

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 170, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Họ tên:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Email:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 30));

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(51, 153, 255));
        btnCapNhat.setText("Cập nhật thông tin ");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 330, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin tài khoản: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 250, 40));

        jlbUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbUsername.setText("username");
        jPanel1.add(jlbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 720, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if ( txtHoTen.getText().isEmpty() || txtDiaChi.getText().isEmpty() || txtEmail.getText().isEmpty()|| txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
        } else {
            TaiKhoanModel tkNew = new TaiKhoanModel();
            tkNew.setMaGV(tkLoggedIn.getMaGV());
            tkNew.setUsername(tkLoggedIn.getUsername());
            tkNew.setPassword(tkLoggedIn.getPassword());
            tkNew.setHoTen(txtHoTen.getText());        
            tkNew.setNgaySinh(datePkNgaySinh.getDate());
            tkNew.setDiaChi(txtDiaChi.getText());
            tkNew.setEmail(txtEmail.getText());
         
            try {
                tkNew.setSDT(txtSDT.getText());
                suaTaiKhoan(tkNew, listTK.indexOf(tkNew));
                JOptionPane.showMessageDialog(null, "Cập nhật thông tin cá nhân thành công");
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ");
            }    
        }   
    }//GEN-LAST:event_btnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private com.toedter.calendar.JDateChooser datePkNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbUsername;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
