/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NormalUser;

import FileHandle.FileHandleImp;
import Model.PhieuDangKyModel;
import Test.test;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lamng
 */
public class JPThongKeLichTH extends javax.swing.JPanel {
    private ArrayList<PhieuDangKyModel> listPhieuDKByMaGV;
    private FileHandleImp fileHandle;
    public JPThongKeLichTH() {
        fileHandle = new FileHandleImp();
        initComponents();
        loadTable();
    }

    public void loadTable() {
        listPhieuDKByMaGV = fileHandle.getDSPhieuDKByMaGV(test.tk.getMaGV());
        //List maPhong của giáo viên đang đăng nhập
        ArrayList<String> maPhong = new ArrayList<>();
        //List maMon của giáo viên đang đăng nhập
        ArrayList<String> maMon = new ArrayList<>();
        //Set header
        tbLichTH.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        //Danh sách cách cột
        String col[] = {"STT", "Mã lớp","Mã môn", "Mã phòng", "Ca", "Thứ", "Từ ngày", "Đến ngày"};
        DefaultTableModel model = new DefaultTableModel(col, 0);
        int stt = 0;
        SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
        //Thêm dữ liệu
        for (PhieuDangKyModel pdk : listPhieuDKByMaGV) {
            if (pdk.getTrangThai().equals("Đã duyệt")) {
                maPhong.add(pdk.getPth().getMaPhong());
                maMon.add(pdk.getMh().getMaMH());
                stt++;
                Object[] obj = {stt, pdk.getLh().getMaLop(), pdk.getMh().getMaMH(), 
                pdk.getPth().getMaPhong(), pdk.getCa(), pdk.getThu(), 
                fm.format(pdk.getTuNgay()), fm.format(pdk.getDenNgay())};
                model.addRow(obj);
            }
        }
        
        tbLichTH.setModel(model);
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tbLichTH.getModel());
        tbLichTH.setRowSorter(rowSorter);

        //Set combobox
        cboMaPhong.setModel(new DefaultComboBoxModel(maPhong.toArray()));
        cboMaPhong.setSelectedIndex(-1);
        cboMaMon.setModel(new DefaultComboBoxModel(maMon.toArray()));
        cboMaMon.setSelectedIndex(-1);
        
        //Loc theo ma phong
        cboMaPhong.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = cboMaPhong.getSelectedItem().toString();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
        });
        
        //Loc theo ma mon
        cboMaMon.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = cboMaMon.getSelectedItem().toString();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLichTH = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboMaPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboMaMon = new javax.swing.JComboBox<>();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 910, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thống kê lịch thực hành");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tbLichTH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbLichTH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lớp", "Mã môn", "Mã phòng", "Ca", "Thứ", "Từ ngày", "Đến ngày"
            }
        ));
        tbLichTH.setRowHeight(25);
        jScrollPane1.setViewportView(tbLichTH);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 860, 310));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LỊCH THỰC HÀNH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Theo môn:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 30));

        cboMaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboMaPhong.setSelectedIndex(-1);
        jPanel1.add(cboMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Theo phòng máy:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 120, 30));

        jPanel1.add(cboMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMaMon;
    private javax.swing.JComboBox<String> cboMaPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbLichTH;
    // End of variables declaration//GEN-END:variables
}
